_BASE_: "../Base_Infant.yaml"
EXPERIMENT_NAME: 'HRNet'
WORKERS: 1
GPUS: (1,)
OUTPUT_DIR: '/home/mbl/HDD_disk/infant_video/實驗收案/HPE_dataset/Pull_to_sit_20210412_5sec/output/PE/HRnet/'


CORE_FUNCTION: CommonFunction

MODEL:
  NAME: HRNet

  USE_PRF: true
  PRF_BASICBLOCK_NUM: 2
  PRF_INNER_CH: 34

  USE_PTM: true
  PTM_BASICBLOCK_NUM: 1
  PTM_INNER_CH: 17

  USE_PCN: true
  PRF_PTM_COMBINE_BASICBLOCK_NUM: 2
  PRF_PTM_COMBINE_INNER_CH: 64

  DEFORMABLE_CONV:
    DILATION:
      - 3
      - 6
      - 9
      - 12
      - 15
    AGGREGATION_TYPE: weighted_sum
LOSS:
  USE_TARGET_WEIGHT: true

TRAIN:
  AUTO_RESUME: true
  SAVE_MODEL_PER_EPOCH: 1
  BATCH_SIZE_PER_GPU: 8

VAL:
  BATCH_SIZE_PER_GPU: 1
  MODEL_FILE: ''
TEST:
  BATCH_SIZE_PER_GPU: 1
  MODEL_FILE: ''

DEBUG:
  VIS_SKELETON: true
  VIS_BBOX: false
